remove @ character
FlowCrypt/comment-email-address-alerts pull request #4
Opened 2022-04-08 02:33 UTC by martgil

This PR will remove the appending '@' chars to correct expected behavior:

assume exemptedDomains: test, flowcrypt.com

processed exemptedDomains: @test, @flowcrypt.com
current behavior: demo@hello.test - produces unwanted comment notification

processed exemptedDomains: test, flowcrypt.com
corrected behavior: demo@hello.test - do not show comment notification

2022-04-11 10:27 UTC, IvanPizhenko commented
It is wrong premise. You have to add explicitly "hello.test" to the list of domains to avoid warning on it. If you want to have to have all subdomains of ".test" to be ignored likely requires more sophisticated logic than what you suggest.

2022-04-11 10:35 UTC, IvanPizhenko commented
The logic still not competely correct. To achieve the logic in the correct way, you have to map build array of domains containing following for each configured domain: '@' + configured, '.' + configured domain. This will let us avoid false negatives:
```
something@domain.test <-- should not give warning
somehting@domain.bigtest <-- MUST BE WARNING
```

2022-04-11 10:37 UTC, IvanPizhenko requested changes
Please see my comments

2022-04-12 06:00 UTC, martgil commented
thank you for reviewing this - I'm happy to see you, sir.

I accidentally deleted my forked version of this repo so I had to write another [PR](https://github.com/FlowCrypt/comment-email-address-alerts/pull/5). I have successfully achieve the goal we want (I think).

you can also test the update through https://github.com/martgil/test-repo4/issues/4

we may close this pr anytime. thanks

2022-04-15 04:52 UTC, closed without merging